# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: automanlib_rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import automanlib_classes_pb2 as automanlib__classes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='automanlib_rpc.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x14\x61utomanlib_rpc.proto\x1a\x18\x61utomanlib_classes.proto\"%\n\x0b\x41utomanTask\x12\x16\n\x07request\x18\x01 \x01(\x0b\x32\x05.Task\"\xa4\x03\n\x0cTaskResponse\x12\x1d\n\x07outcome\x18\x01 \x01(\x0b\x32\x0c.TaskOutcome\x12\x31\n\x0breturn_code\x18\x02 \x01(\x0e\x32\x1c.TaskResponse.TaskReturnCode\x12/\n\nexcep_code\x18\x03 \x01(\x0e\x32\x1b.TaskResponse.ExceptionCode\x12)\n\x08\x65rr_code\x18\x04 \x01(\x0e\x32\x17.TaskResponse.ErrorCode\x12\x0f\n\x07\x65rr_msg\x18\x05 \x01(\t\x12\x11\n\texcep_msg\x18\x06 \x01(\t\"N\n\x0eTaskReturnCode\x12\x17\n\x13UNDEFINED_RESP_CODE\x10\x00\x12\t\n\x05VALID\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x12\r\n\tEXCEPTION\x10\x03\",\n\rExceptionCode\x12\x1b\n\x17UNDEFINED_EXCPTION_CODE\x10\x00\"D\n\tErrorCode\x12\x18\n\x14UNDEFINED_ERROR_CODE\x10\x00\x12\x1d\n\x19NO_CREDENTIALS_REGISTERED\x10\x01\"\x9c\x01\n\x14RegistrationResponse\x12\x38\n\x0breturn_code\x18\x01 \x01(\x0e\x32#.RegistrationResponse.RegReturnCode\x12\x0f\n\x07message\x18\x02 \x01(\t\"9\n\rRegReturnCode\x12\x12\n\x0eUNDEFINED_CODE\x10\x00\x12\x08\n\x04OKAY\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\"\x97\x01\n\x14ServerStatusResponse\x12\x39\n\x0breturn_code\x18\x01 \x01(\x0e\x32$.ServerStatusResponse.StatReturnCode\"D\n\x0eStatReturnCode\x12\x19\n\x15UNDEFINED_STATUS_CODE\x10\x00\x12\x0b\n\x07RUNNING\x10\x01\x12\n\n\x06KILLED\x10\x02\"\x07\n\x05\x45mpty2\xe3\x01\n\x13\x45stimationPrototype\x12-\n\nKillServer\x12\x06.Empty\x1a\x15.ServerStatusResponse\"\x00\x12?\n\x0fRegisterAdapter\x12\x13.AdapterCredentials\x1a\x15.RegistrationResponse\"\x00\x12+\n\nSubmitTask\x12\x0c.AutomanTask\x1a\r.TaskResponse\"\x00\x12/\n\x0cServerStatus\x12\x06.Empty\x1a\x15.ServerStatusResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[automanlib__classes__pb2.DESCRIPTOR,])



_TASKRESPONSE_TASKRETURNCODE = _descriptor.EnumDescriptor(
  name='TaskReturnCode',
  full_name='TaskResponse.TaskReturnCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED_RESP_CODE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VALID', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXCEPTION', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=316,
  serialized_end=394,
)
_sym_db.RegisterEnumDescriptor(_TASKRESPONSE_TASKRETURNCODE)

_TASKRESPONSE_EXCEPTIONCODE = _descriptor.EnumDescriptor(
  name='ExceptionCode',
  full_name='TaskResponse.ExceptionCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED_EXCPTION_CODE', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=396,
  serialized_end=440,
)
_sym_db.RegisterEnumDescriptor(_TASKRESPONSE_EXCEPTIONCODE)

_TASKRESPONSE_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='TaskResponse.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED_ERROR_CODE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_CREDENTIALS_REGISTERED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=442,
  serialized_end=510,
)
_sym_db.RegisterEnumDescriptor(_TASKRESPONSE_ERRORCODE)

_REGISTRATIONRESPONSE_REGRETURNCODE = _descriptor.EnumDescriptor(
  name='RegReturnCode',
  full_name='RegistrationResponse.RegReturnCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED_CODE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OKAY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=612,
  serialized_end=669,
)
_sym_db.RegisterEnumDescriptor(_REGISTRATIONRESPONSE_REGRETURNCODE)

_SERVERSTATUSRESPONSE_STATRETURNCODE = _descriptor.EnumDescriptor(
  name='StatReturnCode',
  full_name='ServerStatusResponse.StatReturnCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED_STATUS_CODE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUNNING', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KILLED', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=755,
  serialized_end=823,
)
_sym_db.RegisterEnumDescriptor(_SERVERSTATUSRESPONSE_STATRETURNCODE)


_AUTOMANTASK = _descriptor.Descriptor(
  name='AutomanTask',
  full_name='AutomanTask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='AutomanTask.request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=87,
)


_TASKRESPONSE = _descriptor.Descriptor(
  name='TaskResponse',
  full_name='TaskResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='outcome', full_name='TaskResponse.outcome', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='return_code', full_name='TaskResponse.return_code', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='excep_code', full_name='TaskResponse.excep_code', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err_code', full_name='TaskResponse.err_code', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err_msg', full_name='TaskResponse.err_msg', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='excep_msg', full_name='TaskResponse.excep_msg', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TASKRESPONSE_TASKRETURNCODE,
    _TASKRESPONSE_EXCEPTIONCODE,
    _TASKRESPONSE_ERRORCODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=510,
)


_REGISTRATIONRESPONSE = _descriptor.Descriptor(
  name='RegistrationResponse',
  full_name='RegistrationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='return_code', full_name='RegistrationResponse.return_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='RegistrationResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REGISTRATIONRESPONSE_REGRETURNCODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=513,
  serialized_end=669,
)


_SERVERSTATUSRESPONSE = _descriptor.Descriptor(
  name='ServerStatusResponse',
  full_name='ServerStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='return_code', full_name='ServerStatusResponse.return_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SERVERSTATUSRESPONSE_STATRETURNCODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=672,
  serialized_end=823,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=825,
  serialized_end=832,
)

_AUTOMANTASK.fields_by_name['request'].message_type = automanlib__classes__pb2._TASK
_TASKRESPONSE.fields_by_name['outcome'].message_type = automanlib__classes__pb2._TASKOUTCOME
_TASKRESPONSE.fields_by_name['return_code'].enum_type = _TASKRESPONSE_TASKRETURNCODE
_TASKRESPONSE.fields_by_name['excep_code'].enum_type = _TASKRESPONSE_EXCEPTIONCODE
_TASKRESPONSE.fields_by_name['err_code'].enum_type = _TASKRESPONSE_ERRORCODE
_TASKRESPONSE_TASKRETURNCODE.containing_type = _TASKRESPONSE
_TASKRESPONSE_EXCEPTIONCODE.containing_type = _TASKRESPONSE
_TASKRESPONSE_ERRORCODE.containing_type = _TASKRESPONSE
_REGISTRATIONRESPONSE.fields_by_name['return_code'].enum_type = _REGISTRATIONRESPONSE_REGRETURNCODE
_REGISTRATIONRESPONSE_REGRETURNCODE.containing_type = _REGISTRATIONRESPONSE
_SERVERSTATUSRESPONSE.fields_by_name['return_code'].enum_type = _SERVERSTATUSRESPONSE_STATRETURNCODE
_SERVERSTATUSRESPONSE_STATRETURNCODE.containing_type = _SERVERSTATUSRESPONSE
DESCRIPTOR.message_types_by_name['AutomanTask'] = _AUTOMANTASK
DESCRIPTOR.message_types_by_name['TaskResponse'] = _TASKRESPONSE
DESCRIPTOR.message_types_by_name['RegistrationResponse'] = _REGISTRATIONRESPONSE
DESCRIPTOR.message_types_by_name['ServerStatusResponse'] = _SERVERSTATUSRESPONSE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AutomanTask = _reflection.GeneratedProtocolMessageType('AutomanTask', (_message.Message,), dict(
  DESCRIPTOR = _AUTOMANTASK,
  __module__ = 'automanlib_rpc_pb2'
  # @@protoc_insertion_point(class_scope:AutomanTask)
  ))
_sym_db.RegisterMessage(AutomanTask)

TaskResponse = _reflection.GeneratedProtocolMessageType('TaskResponse', (_message.Message,), dict(
  DESCRIPTOR = _TASKRESPONSE,
  __module__ = 'automanlib_rpc_pb2'
  # @@protoc_insertion_point(class_scope:TaskResponse)
  ))
_sym_db.RegisterMessage(TaskResponse)

RegistrationResponse = _reflection.GeneratedProtocolMessageType('RegistrationResponse', (_message.Message,), dict(
  DESCRIPTOR = _REGISTRATIONRESPONSE,
  __module__ = 'automanlib_rpc_pb2'
  # @@protoc_insertion_point(class_scope:RegistrationResponse)
  ))
_sym_db.RegisterMessage(RegistrationResponse)

ServerStatusResponse = _reflection.GeneratedProtocolMessageType('ServerStatusResponse', (_message.Message,), dict(
  DESCRIPTOR = _SERVERSTATUSRESPONSE,
  __module__ = 'automanlib_rpc_pb2'
  # @@protoc_insertion_point(class_scope:ServerStatusResponse)
  ))
_sym_db.RegisterMessage(ServerStatusResponse)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'automanlib_rpc_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  ))
_sym_db.RegisterMessage(Empty)



_ESTIMATIONPROTOTYPE = _descriptor.ServiceDescriptor(
  name='EstimationPrototype',
  full_name='EstimationPrototype',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=835,
  serialized_end=1062,
  methods=[
  _descriptor.MethodDescriptor(
    name='KillServer',
    full_name='EstimationPrototype.KillServer',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_SERVERSTATUSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RegisterAdapter',
    full_name='EstimationPrototype.RegisterAdapter',
    index=1,
    containing_service=None,
    input_type=automanlib__classes__pb2._ADAPTERCREDENTIALS,
    output_type=_REGISTRATIONRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SubmitTask',
    full_name='EstimationPrototype.SubmitTask',
    index=2,
    containing_service=None,
    input_type=_AUTOMANTASK,
    output_type=_TASKRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ServerStatus',
    full_name='EstimationPrototype.ServerStatus',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_SERVERSTATUSRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ESTIMATIONPROTOTYPE)

DESCRIPTOR.services_by_name['EstimationPrototype'] = _ESTIMATIONPROTOTYPE

# @@protoc_insertion_point(module_scope)
